### ISSUE TITLE
startCameraMaxResolution is not Throwing excepcion or reject

### ISSUE THREAD

**Issue by cbeltrangomez84** [MABelanger/jslib-html5-camera-photo#9]
When I try to start a camera in max resolution when I have not camera connected, the "catch" block is not executed but errors apears in console.

**Comment by cbeltrangomez84** [comment]
In _getStreamDeviceMaxResolution function, in line 62 `this._getStreamDeviceMaxResolution(idealFacingMode);` we need to add a then and catch statement, with the catch rejecting the promise.

like this:

`setTimeout(() => {
            this.numberOfMaxResolutionTry += 1;
            this._getStreamDeviceMaxResolution(idealFacingMode)
              .then(() => {resolve()})
              .catch(() => {    
                reject({name, constraint, message})
              });
          }, 20);`

would love to colaborate and commit and push my changes, but to be honest I don't know how to collaborate with git projects. I'd receive advise happily.

**Comment by cbeltrangomez84** [comment]
Just try my first pull request. Sorry in advance for any mistake.

**Comment by quickshiftin** [comment]
@MABelanger  I stumbled into this issue when trying to handle the scenario where a user has blocked camera access. It is currently broken, because of this bug in the "stable" version on npm (3.0.2-beta.0).

I [forked the library](https://github.com/quickshiftin/jslib-html5-camera-photo/tree/stable) right at that version where the stable branch was built, and applied this patch. Long story short, the library now properly handles a blocked camera! I highly suggest you apply this patch in similar vein.

@cbeltrangomez84 - thank you sir!!!

**Comment by MABelanger** [comment]
@cbeltrangomez84 @quickshiftin  Thank for report, fix on version 3.1.2. Sorry for the delay
